### ISSUE TITLE
container_networking* Metrics Missing Labels after K8S 1.30.1 Upgrade

### ISSUE THREAD

**Issue by johnmwood** [google/cadvisor#3551]
My team recently upgraded from K8S v1.29.5 to v1.30.1. We noticed all metrics for `container_network*` immediately drop labels. When checking our metrics endpoint, here are a few examples:
```
kubectl get --raw /api/v1/nodes/NODE/proxy/metrics/cadvisor 

container_network_receive_errors_total{container="",id="/",image="",interface="bond0",name="",namespace="",pod=""} 1634 1718830359399

container_network_receive_errors_total{container="",id="/",image="",interface="bond0",name="",namespace="",pod=""} 1634 1718830359399

container_network_receive_packets_dropped_total{container="",id="/",image="",interface="bond0",name="",namespace="",pod=""} 2.907596e+06 1718830359399
```

This has broken our existing prometheus queries for these metrics. 

## Environment
* Runtime: cri-o
* Image: Debian Bookworm
* K8S: v1.30.1
* cgroup-driver: systemd
 
## Potentially related issues
* [K8s/cri-o broken for cgroup-driver != systemd](https://github.com/google/cadvisor/issues/3538)
* [Not able to view container names for network metrics](https://github.com/google/cadvisor/issues/3323)
* [Cadvisor Metrics Label contain empty Strings as values (container="", image="",...)](https://github.com/google/cadvisor/issues/3336)

**Comment by nicolas-laduguie** [comment]
Hi, any news on that issue ?

**Comment by nick-oconnor** [comment]
@haircommander any ideas what could have caused this? I lost all `container_network_` metrics on 1.30 w/ cri-o + systemd. This seems like another cri-o/systemd/cadvisor issue.

**Comment by haircommander** [comment]
https://github.com/kubernetes/kubernetes/pull/129133 should fix this in 1.30, sorry for the delay

**Comment by shapirus** [comment]
> [kubernetes/kubernetes#129133](https://github.com/kubernetes/kubernetes/pull/129133) should fix this in 1.30, sorry for the delay

All it does is update cadvisor to v0.49.2, as it seems to me.

I'm having this same issue with a standalone cadvisor daemonset on various versions of kubernetes up to 1.28.0 (all using containerd).

Almost all labels are missing for network metrics, and the only ones present are "interface" and "id", e.g.

```
container_network_receive_bytes_total{[...a bunch of labels with empty values...],id="/",image="",interface="lxc13778fbe922c",name=""} 21166 1741805424662
```

How do I debug whether it's a cadvisor issue or that of the source where cadvisor collects the metrics?

**Comment by vstariradev** [comment]
Still reproducible on kubernetes v1.31.8 . `container` labels are empty for all `container_network_*` metrics. Containerd version is 1.7.27

`kubectl get --raw /api/v1/nodes/NODE/proxy/metrics/cadvisor`

```container_network_transmit_packets_total{container="",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podfc03096d_0780_4b40_bd1a_2d00f7176caa.slice/cri-containerd-fd6cd07f65af5beeeca817f7596508f0fbad93b2a946ba0c2a013e181823ef9b.scope",image="registry.k8s.io/pause:3.9",interface="eth0",name="fd6cd07f65af5beeeca817f7596508f0fbad93b2a946ba0c2a013e181823ef9b",namespace="tooling",pod="kubernetes-oomkill-exporter-lkmhr"} 104504 1752068017025```

**Comment by evgkrsk** [comment]
Same problem with containerd-1.7.x, k8s-1.29/1.31.

**Comment by evgkrsk** [comment]
Interesting that "pause:3"-based container has network metrics just right.
