### ISSUE TITLE
POD Networking metrics missing with crio-1.30 and kubelet-1.30

### ISSUE THREAD

**Issue by rkojedzinszky** [google/cadvisor#3577]
It seems that https://github.com/google/cadvisor/commit/eac1257f76a4a55bb2bf836f41a577a2fcb148a4 breaks network metric collection. At least, with crio-1.30 with defaults.

If I apply the simple diff, I can get container metrics again:

```diff
--- a/vendor/github.com/google/cadvisor/container/crio/handler.go
+++ b/vendor/github.com/google/cadvisor/container/crio/handler.go
@@ -155,6 +155,7 @@ func newCrioContainerHandler(
        // reported. This stops metrics being reported multiple times for each
        // container in a pod.
        metrics := common.RemoveNetMetrics(includedMetrics, cInfo.Labels["io.kubernetes.container.name"] != "POD")
+       metrics = includedMetrics
 
        libcontainerHandler := containerlibcontainer.NewHandler(cgroupManager, rootFs, cInfo.Pid, metrics)
 ```

The command used to test this:

```
curl -s -H "Authorization: bearer $TOKEN" -k https://192.168.111.122:10250/metrics/cadvisor | grep "^container_network_transmit_packets_total"
```

Perhaps, cri-o does not have or keep a `POD` named container?

**Comment by rkojedzinszky** [comment]
It seems that, if I set `drop_infra_ctr = false` in crio.conf, it also solves the problem.

**Comment by kwilczynski** [comment]
Cc @kolyshkin, the author of the mentioned Pull Request.

**Comment by kolyshkin** [comment]
From a cursory look, commit eac1257 does not change the metrics being reported. If you take a look at the (removed) `needNet` method and its usage in the code before the commit, you will see that the metrics were dropped (after collecting) using the same criterion (checking if "io.kubernetes.container.name" label is "POD").

**Comment by kolyshkin** [comment]
To fix the issue, I guess the criteria used for excluding network metrics (i.e. the second argument of `common.RemoveNetMetrics`)  should be different depending on whether cri-o uses infra container or not. Perhaps @haircommander can shed more light.

**Comment by sohankunkerkar** [comment]
I think [this](https://github.com/google/cadvisor/commit/eac1257f76a4a55bb2bf836f41a577a2fcb148a4#diff-6880ecff5f83b0d1f52fc5ee7799f8967af4235d16b214a48bea0ad799a752e8R157) piece of code will not work for CRI-O. If the infra container has empty network metrics, the crio handler uses a running container in the pod to gather the metrics. Therefore, metrics must be collected from all containers to ensure that if there's a running container in the podthe necessary metrics are gathered.

**Comment by kolyshkin** [comment]
> I think [this](https://github.com/google/cadvisor/commit/eac1257f76a4a55bb2bf836f41a577a2fcb148a4#diff-6880ecff5f83b0d1f52fc5ee7799f8967af4235d16b214a48bea0ad799a752e8R157) piece of code will not work for CRI-O. If the infra container has empty network metrics, the crio handler uses a running container in the pod to gather the metrics. Therefore, metrics must be collected from all containers to ensure that if there's a running container in the podthe necessary metrics are gathered.

This is what I meant in [the comment above](https://github.com/google/cadvisor/issues/3577#issuecomment-2290739160) -- find a way to see if infra container is used, and fix the second argument to `common.RemoveNetMetrics` accordingly.

**Comment by haircommander** [comment]
cri-o should still be creating an empty cgroup for the infra container so cadvisor is aware of it, and then reporting the PID of the infra container as being one of the other containers in the pod (so network metrics can be collected). It's possible something in that broke, we should make sure cadvisor is sees the infra container cgroup (and that cri-o create it)

**Comment by haircommander** [comment]
I actually think https://github.com/google/cadvisor/commit/ca820b635076e6d7bfb85b39202836157966cb7b would fix this. @iwankgb do you think it'd be possible to cherry-pick this to a 0.49.1 (that we create after the pick) so we can pull into kubernetes 1.30?

**Comment by iwankgb** [comment]
@haircommander I would love to help, but I am not able to cut a release. Someone from Google (@bobbypage, is this still you?) needs to do this.

**Comment by rkojedzinszky** [comment]
Any updates on this?

**Comment by giovannicandido** [comment]
Any update?

**Comment by dipaksawle** [comment]
Any update on this? We are facing the issue in 1.30.5 and 1.31.4
Not getting pod level metrics.

`container_network_receive_bytes_total{container="",id="/",image="",interface="tunl0",name="",namespace="",pod=""} 
`

**Comment by haircommander** [comment]
the fix merged in upstream kube today! so it should land in the next release of kube 1.30

**Comment by makeittotop** [comment]
We are still facing this issue on  kube v1.31.8,  cri-o v1.31.5, kubelet v1.31.8. Are you sure this issue has been fixed @haircommander ? 

`container_network_transmit_packets_total{container="",id="/",image="",interface="lxcba2058424e23",name="",namespace="",pod=""} 168717 1749587254578
container_network_transmit_packets_total{container="",id="/",image="",interface="lxcc4fe55b7853f",name="",namespace="",pod=""} 1 1749587254578
container_network_transmit_packets_total{container="",id="/",image="",interface="lxcd17374638a5f",name="",namespace="",pod=""} 117261 1749587254578
container_network_transmit_packets_total{container="",id="/",image="",interface="lxcd538bd8f9fb5",name="",namespace="",pod=""} 323866 1749587254578
container_network_transmit_packets_total{container="",id="/",image="",interface="lxcda8aeef5ef24",name="",namespace="",pod=""} 0 1749587254578
container_network_transmit_packets_total{container="",id="/",image="",interface="lxcf64ffafb77f6",name="",namespace="",pod=""} 64950 1749587254578
container_network_transmit_packets_total{container="",id="/",image="",interface="lxcffd627f94e15",name="",namespace="",pod=""} 180204 1749587254578
`

**Comment by bingikarthik** [comment]
Hi,
Any update on when this issue will be fixed and which kubernetes version that this issue will be fixed?
We're also impacted by the missing network metrics issue and are currently running Kubernetes version `1.31.7`!

**Comment by haircommander** [comment]
unfortunately I don't think the PR is going to be backported to 1.31 at this point. I would recommend upgrading to 1.32

**Comment by rkojedzinszky** [comment]
Have checked with k8s 1.33, seems to be fixed.

**Comment by NareshKoduru** [comment]
Greetings,
Can this be backported to 1.32?
